### ISSUE TITLE
vcr is not handling recording bodies in POST requests

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#143]
e.g, 

```r
library(rgbif)
occ_download(pred("taxonKey", 9206251),
      pred_in("country", c("US", "MX")), pred_gte("year", 1982))
```

```yaml
http_interactions:
- request:
    method: post
    uri: https://api.gbif.org/v1/occurrence/download/request
    body:
      encoding: ''
      string: ''
    headers:
      Accept-Encoding: gzip, deflate
      User-Agent: r-curl/4.3 crul/0.9.0 rOpenSci(rgbif/2.0.0.91)
      X-USER-AGENT: r-curl/4.3 crul/0.9.0 rOpenSci(rgbif/2.0.0.91)
      Content-Type: application/json
      Accept: application/json

...
```

body - string - should not be empty in the request
