### ISSUE TITLE
support looping through responses for the same request?

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#190]
Context: At the moment for faking some behavior of the server (e.g. an error, or simpler responses to decrease the fixture size) one needs to use webmockr.
This is not ideal as it's quite different from vcr.

One alternative is
* write your test and use_cassette() around the code calling the API.
* run the test
* edit the cassette by hand

It's quite handy IMHO.

Now, one thing that this workflow can't handle is testing retries. So I wonder whether there'd be a way to add a field "count" to the fixture and e.g. have

```yaml
http_interactions:
- request:
    count: 1
    method: get
    uri: https://kctbh9vrtdwd.statuspage.io/api/v2/components.json
    body:
      encoding: ''
      string: ''
    headers:
      Accept: application/json, text/xml, application/xml, */*
  response:
    - count: 1
      status_code: 502
    - count: 2
      status_code: 200

```

and vcr would loop through the responses?
