### ISSUE TITLE
Request bodies are not being recorded correctly with httr2

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#276]
```r
library(vcr)
library(httr2)
use_cassette("apple", 
  request("https://hb.cran.dev/post") %>% 
    req_body_json('{"a": 66666}') %>% 
    req_perform()
)
```

yaml file has:

```yaml
http_interactions:
- request:
    method: post
    uri: https://hb.cran.dev/post
    body:
      encoding: ''
      string: '' # <- should be a body here
    headers: []
  response:
    status:
      status_code: 200
      message: OK
    headers:
      ...
```

**Comment by sckott** [comment]
@hadley Do you know if there's a way in either/both of `httr` and `httr2` to get the request body data sent in a http request? Without modifying any code that is in either package. 

Context is that I'm trying to follow what other vcr packages do in other langs here for request bodies. It seems they put the data actually sent in the HTTP request rather than some naive approach of putting just the data or file path thats supplied to the request body.  

Here's a Python example:

<details><summary>script: examples.py</summary>
<p>

```python
# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "httpx",
#     "pytest",
#     "vcrpy",
# ]
# ///
import httpx
import vcr
import pytest
from pathlib import Path

my_vcr = vcr.VCR(
    cassette_library_dir="tests/fixtures/cassettes",
    record_mode="once",
    match_on=["uri", "method", "body"],
)


@pytest.mark.vcr()
def test_file_upload():
    test_file_path = Path("test_upload.txt")
    with open(test_file_path, "w") as f:
        f.write("Test file content")

    with httpx.Client() as client:
        files = {"file": ("test_upload.txt", open(test_file_path, "rb"), "text/plain")}

        data = {"title": "My Document", "description": "Test file upload"}

        response = client.post("https://hb.cran.dev/post", files=files, data=data)

        assert response.status_code == 200


@pytest.mark.vcr()
def test_json_upload():
    with httpx.Client() as client:
        data = {"integer": 123, "boolean": True, "list": ["a", "b", "c"]}

        response = client.post("https://hb.cran.dev/post", json=data)

        assert response.status_code == 200


@pytest.mark.vcr()
def test_form_upload():
    with httpx.Client() as client:
        data = {"key1": "value1", "key2": "value2"}

        response = client.post("https://hb.cran.dev/post", data=data)

        assert response.status_code == 200


@pytest.mark.vcr()
def test_binary_upload():
    with httpx.Client() as client:
        content = b"Hello, world"

        response = client.post("https://hb.cran.dev/post", content=content)

        assert response.status_code == 200

```

</p>
</details> 


If you run `uv run pytest --record-mode=once examples.py` (I assume you have `uv`?) you'll get 4 cassettes. Here's the request bodies they store:

__file__

```yaml
interactions:
- request:
    body: "--e1739e92244e1aa989372b244d91d6df\r\nContent-Disposition: form-data; name=\"title\"\r\n\r\nMy
      Document\r\n--e1739e92244e1aa989372b244d91d6df\r\nContent-Disposition: form-data;
      name=\"description\"\r\n\r\nTest file upload\r\n--e1739e92244e1aa989372b244d91d6df\r\nContent-Disposition:
      form-data; name=\"file\"; filename=\"test_upload.txt\"\r\nContent-Type: text/plain\r\n\r\nTest
      file content\r\n--e1739e92244e1aa989372b244d91d6df--\r\n"
```

__json__

```yaml
interactions:
- request:
    body: '{"integer": 123, "boolean": true, "list": ["a", "b", "c"]}'
```

__form__

```yaml
interactions:
- request:
    body: key1=value1&key2=value2
```

__binary__

```yaml
interactions:
- request:
    body: Hello, world
```


json, form and binary are easy enough to determine myself in vcr, but the file data would be nice to get from httr/httr2/crul. the data can be retrieved from the http response as we don't write the cassette until after the request has been made and response returned. Or if we can create the data beforehand that'd be a good option (perhaps via `curl_echo`, but maybe that's too heavy).
